productsSample = [
    "Bạn có biết tại sao chúng ta cần tái chế các thiết bị điện tử cũ như điện thoại không?",
    "Giảm lượng rác thải điện tử bằng cách nào?",
    "Cách làm hệ thống tưới nhỏ giọt từ chai nhựa?",
    "Chúng ta nên làm gì với các pin cũ từ điện thoại sau khi chúng không còn sử dụng được nữa?",
    "Bạn có biết cách phân loại rác thải điện tử không?",
    "Lợi ích của việc tái chế điện thoại di động là gì?",
    "Tại sao chúng ta nên chọn các sản phẩm điện tử bền vững?",
    "Điện thoại di động cũ có thể được tái chế thành những sản phẩm nào?",
    "Chúng ta có thể giảm thiểu tác động môi trường bằng cách nào khi sử dụng các thiết bị điện tử?",
    "Bạn có biết làm thế nào để tiết kiệm năng lượng khi sử dụng các thiết bị điện tử không?",
    "Những yếu tố nào cần xem xét khi mua một sản phẩm điện tử mới để bảo vệ môi trường?",
    "Tại sao việc mua các thiết bị điện tử đã qua sử dụng lại có lợi cho môi trường?",
    "Điện thoại tái chế có giúp giảm lượng rác thải nhựa không?",
    "Có những sáng kiến nào giúp giảm thiểu rác thải điện tử tại trường học?",
    "Làm thế nào để bảo quản thiết bị điện tử để kéo dài tuổi thọ của chúng?",
    "Bạn có thể nêu ví dụ về một số chương trình tái chế thiết bị điện tử ở địa phương không?",
    "Chúng ta có thể làm gì để thúc đẩy việc tái chế trong cộng đồng của mình?",
    "Các công nghệ mới có thể giúp giảm lượng rác thải điện tử như thế nào?",
    "Điện thoại thông minh tái chế có ảnh hưởng như thế nào đến môi trường?",
    "Bạn có biết về bất kỳ chương trình thu hồi điện thoại cũ nào không?",
    "Tại sao việc tái chế kim loại từ điện thoại di động lại quan trọng?",
    "Chúng ta nên làm gì với các thiết bị điện tử không còn hoạt động?",
    "Bạn có thể chia sẻ về tầm quan trọng của việc sử dụng các sản phẩm điện tử thân thiện với môi trường không?",
    "Có những lựa chọn nào để thay thế các thiết bị điện tử cũ thay vì vứt bỏ chúng?",
    "Việc sử dụng lại các thiết bị điện tử cũ có thể giúp ích gì cho môi trường?",
    "Bạn có biết cách giảm thiểu rác thải điện tử trong cuộc sống hàng ngày không?",
    "Có cách nào để biến rác thải điện tử thành tài nguyên có ích không?",
    "Bạn có biết làm thế nào để xử lý các thiết bị điện tử đã hỏng một cách an toàn không?",
    "Tại sao chúng ta nên tránh việc mua sắm thiết bị điện tử không cần thiết?",
    "Bạn có thể giải thích lợi ích của việc mua thiết bị điện tử có tuổi thọ cao không?",
    "Những hành động cụ thể nào chúng ta có thể làm để giảm thiểu rác thải điện tử?",
    "Tái chế điện thoại cũ có giúp giảm bớt việc khai thác tài nguyên thiên nhiên không?",
    "Chúng ta có thể làm gì để khuyến khích việc tái chế điện tử trong gia đình?",
    "Bạn có biết các công ty nào có chương trình tái chế điện tử không?",
    "Làm thế nào để chọn mua thiết bị điện tử vừa đáp ứng nhu cầu vừa bảo vệ môi trường?",
    "Có những loại điện thoại nào được sản xuất từ vật liệu tái chế không?",
    "Những lưu ý nào khi sử dụng thiết bị điện tử để giảm thiểu tác động đến môi trường?",
    "Tại sao việc bảo quản pin điện thoại đúng cách lại quan trọng đối với môi trường?",
    "Chúng ta có thể tìm hiểu thông tin về tái chế điện tử từ đâu?",
    "Có những dự án nào trong trường học liên quan đến tái chế thiết bị điện tử không?",
    "Bạn có thể giải thích về quy trình tái chế một chiếc điện thoại di động không?",
    "Có những sáng kiến nào tại địa phương hỗ trợ việc tái chế rác thải điện tử?",
    "Làm thế nào để các bạn học sinh có thể tham gia vào hoạt động tái chế điện tử?",
    "Tại sao chúng ta nên chọn các thiết bị điện tử có khả năng tái chế cao?",
    "Việc bảo dưỡng điện thoại có thể giúp giảm thiểu rác thải điện tử như thế nào?",
    "Có những mẹo nào để sử dụng thiết bị điện tử một cách bền vững không?",
    "Tại sao chúng ta cần quan tâm đến tuổi thọ của thiết bị điện tử?",
    "Những nguyên liệu nào từ điện thoại cũ có thể được tái sử dụng?",
    "Bạn có biết cách xử lý các thiết bị điện tử cũ một cách an toàn không?",
    "Những chương trình nào hỗ trợ tái chế điện thoại di động tại địa phương?"
]



chitchatSample = [
    "Thời tiết hôm nay như thế nào?",
    "Ngoài trời nóng bao nhiêu?",
    "Ngày mai có mưa không?",
    "Nhiệt độ hiện tại là bao nhiêu?",
    "Bạn có thể cho tôi biết điều kiện thời tiết hiện tại không?",
    "Cuối tuần này có nắng không?",
    "Nhiệt độ hôm qua là bao nhiêu?",
    "Đêm nay trời sẽ lạnh đến mức nào?",
    "Ai là tổng thống đầu tiên của Hoa Kỳ?",
    "Chiến tranh thế giới thứ hai kết thúc vào năm nào?",
    "Bạn có thể kể cho tôi về lịch sử của internet không?",
    "Tháp Eiffel được xây dựng vào năm nào?",
    "Ai đã phát minh ra điện thoại?",
    "Tên của bạn là gì?",
    "Bạn có tên không?",
    "Tôi nên gọi bạn là gì?",
    "Ai đã tạo ra bạn?",
    "Bạn bao nhiêu tuổi?",
    "Bạn có thể kể cho tôi một sự thật thú vị không?",
    "Bạn có biết bất kỳ câu đố thú vị nào không?",
    "Màu sắc yêu thích của bạn là gì?",
    "Bộ phim yêu thích của bạn là gì?",
    "Bạn có sở thích nào không?",
    "Ý nghĩa của cuộc sống là gì?",
    "Bạn có thể kể cho tôi một câu chuyện cười không?",
    "Thủ đô của Pháp là gì?",
    "Dân số thế giới là bao nhiêu?",
    "Có bao nhiêu châu lục?",
    "Ai đã viết 'Giết con chim nhại'?",
    "Bạn có thể cho tôi một câu nói của Albert Einstein không?"
]